### ISSUE TITLE
NaiwaziBot-V4.0.3

### ISSUE THREAD

**Issue by cxsorious** [Naiwazi/NaiwaziBot#3]
I Used on A21.1 and A21.2 (B30)
I think there's a problem. Is it about zombies freezing?
Please make sure that can work properly.
Thanks :) Love NaiwaziBot

**Comment by Naiwazi** [comment]
Hi there,
NaiwaziBot has no any hooks, and do nothing with zombies, no one complain
about zombies freezing, besides, TFP had already fixed the bugs about
zombie freezing since the beginnings of A21, I think you could check your
mods to make sure if something goes wrong with that.

Regards,
Rainyeve.

CXSOIROUS ***@***.***>于2023年11月27日 周一下午8:00写道：

**Comment by cxsorious** [comment]
Okay, I'll try to find the cause. May not be compatible with 1CSMM_Patrons or ServerTools.

**Comment by cxsorious** [comment]
In the future, I want to have a system Auto_Backup_Map_Delay.
Level_Up Announce and Player's Vehicle callback system.
